### ISSUE TITLE
Bad download from plugin store link

### ISSUE THREAD

**Issue by FlyingDiver** [Ghawken/Indigo-EmbyPlugin#1]
The zip file download unzips to a folder with the version number appended to the .indigoPlugin extension, so it has to be renamed before it can be installed.

**Comment by Ghawken** [comment]
Odd.  Same as all the rest from creation standpoint.  Wonder whether so old..

**Comment by FlyingDiver** [comment]
I know on mine I use the plugin clean and zip script to create a zip file with JUST the plugin in it, and upload that as the release file.

**Comment by FlyingDiver** [comment]
Fixed in 0.1.5.
